apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    visualize: "true"
  name: nginx
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      visualize: "true"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        visualize: "true"
    spec:
      containers:
      - image: buildserver:5000/rpi-nginx-withcontent:3
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
