apiVersion: v1
kind: Service
metadata:
  labels:
    run: cddb-frontend
    visualize: "true"
  name: cddb-frontend
spec:
  externalIPs:
  - 10.150.42.191
  ports:
  - port: 90
    protocol: TCP
    targetPort: 80
  selector:
    run: cddb-frontend
  sessionAffinity: None
  type: NodePort
