apiVersion: v1
kind: Service
metadata:
  labels:
    run: cddb-frontend
    visualize: "true"
  name: cddb-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: cddb-frontend
  sessionAffinity: None
  type: NodePort
