apiVersion: v1
kind: Service
metadata:
  labels:
    run: cddb-backend
    visualize: "true"
  name: cddb-backend
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: cddb-backend
  sessionAffinity: None
  type: ClusterIP
