apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share-x
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: buildserver
    path: "/home/quintor/nfs-share/rpi-node-x"
