apiVersion: v1
kind: PersistentVolume
metadata:
  name: rpi-node-40
spec:
  capacity:
    storage: 1Gi
  accessModes:
    -  ReadWriteOnce
  nfs:
    path: /home/quintor/nfs-share/rpi-node-40
    server: buildserver
  persistentVolumeReclaimPolicy: Retain
