apiVersion: v1
kind: PersistentVolume
metadata:
  name: awassink
spec:
  capacity:
    storage: 1Gi
  accessModes:
    -  ReadWriteOnce
  nfs:
    path: /home/kubedrive/awassink
    server: 10.8.60.182
  persistentVolumeReclaimPolicy: Retain
