apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
    visualize: "true"
  name: nginx
spec:
  externalIPs:
  - <my_node_ip>
  ports:
  - port: <my_portnumber>
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: ClusterIP
