apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: nginx
    visualize: "true"
  name: nginx
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: nginx
        visualize: "true"
    spec:
      containers:
      - image: buildserver:5000/rpi-nginx-withcontent:3
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
