apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx
    visualize: "true"
spec:
  externalIPs:
  - <your node ip>
  ports:
  - port: 90
    protocol: TCP
    targetPort: 80
  selector:
    name: nginx
  sessionAffinity: None
  type: ClusterIP
