apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: cddb-frontend
    visualize: "true"
    uses: "cddb-backend"
  name: cddb-frontend
spec:
  replicas: 2
  strategy:
    type: # define a rolling update strategy for the frontend containers
  template:
    metadata:
      labels:
        run: cddb-frontend
        visualize: "true"
        uses: "cddb-backend"
    spec:
      containers:
      - image: buildserver:5000/rpi-cddb-frontend:v9
        imagePullPolicy: IfNotPresent
        name: cddb-frontend
        ports:
        - containerPort: 80
          protocol: TCP        
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
