apiVersion: v1
kind: Service
metadata:
  labels:
    run: cddb-mysql
    visualize: "true"
  name: cddb-mysql
spec:
  externalIPs:
  - <your node ip>
  ports: # Look this up in the Kubernetes docs (Kubernetes services - port mapping)
  selector:
    run: cddb-mysql
  sessionAffinity: None
  type: # Look this up too, it's critically important and really powerful.
