apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: cddb-mysql
    visualize: "true"
  name: cddb-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cddb-mysql
      visualize: "true"
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: cddb-mysql
        visualize: "true"
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD     # Create kubernetes secrets for these.
          valueFrom:                    # A secret named mysql-root-password
            secretKeyRef:               # that contains a field password
              name: mysql-root-password # http://kubernetes.io/docs/user-guide/secrets/#creating-a-secret-using-kubectl-create-secret
              key: password
        - name: MYSQL_DATABASE
          value: cddb_quintor
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-login
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-login
              key: password
        image: buildserver:5000/rpi-mysql:latest
        imagePullPolicy: IfNotPresent
        name: cddb-mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      dnsPolicy: ClusterFirst
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: cddb-mysql-pv-claim
