apiVersion: v1
kind: Service
metadata:
  labels:
    run: cddb-frontend
    visualize: "true"
  name: cddb-frontend
spec:
  externalIPs:
  - <my_node_ip>
  ports:
  - port: 90
    protocol: TCP
    targetPort: 80
  selector:
    run: cddb-frontend
  sessionAffinity: None
  type: ClusterIP
