apiVersion: v1
kind: PersistentVolume
metadata:
  name: <my_username>
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/kubedrive/<my_sername>
    server: <nfs_server>
  persistentVolumeReclaimPolicy: Retain
