apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${NAME}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/kubedrive/${NAME}
    server: 10.8.60.182
  persistentVolumeReclaimPolicy: Retain
