apiVersion: v1
kind: PersistentVolume
metadata:
  name: <rpi-node-**>
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /home/quintor/nfs-share/<rpi-node-**>
    server: buildserver
  persistentVolumeReclaimPolicy: Retain
